# Aprendizaje Automático

## Tarea 1

Grupo de trabajo:
- Manuel Calderón
- Ernesto Rivera


Primer paso: Importar las bibliotecas necesarias

In [10]:
import math 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import preprocessing
import torch as torch

Siguiente paso: Leer los datos del archivo, que está separado por comas.

In [43]:
# cargar dataframe
df = pd.read_csv("daily-min-temperatures.txt", delimiter=",")
print(df)

            Date  Temp
0     1981-01-01  20.7
1     1981-01-02  17.9
2     1981-01-03  18.8
3     1981-01-04  14.6
4     1981-01-05  15.8
...          ...   ...
3645  1990-12-27  14.0
3646  1990-12-28  13.6
3647  1990-12-29  13.5
3648  1990-12-30  15.7
3649  1990-12-31  13.0

[3650 rows x 2 columns]


In [46]:
# analizar los datos
df.describe()

Temp
count  3650.000000
mean     11.177753
std       4.071837
min       0.000000
25%       8.300000
50%      11.000000
75%      14.000000
max      26.300000

In [45]:
# necesita hacer "reshape" para que transforme de 
# - arreglo de n [20.7000, 17.9000 ...]
# - a matriz de nx1 [[20.7000], [17.9000], ...]] 
temperatura = torch.tensor(df["Temp"]).reshape(-1, 1)
temperatura

tensor([[20.7000],
        [17.9000],
        [18.8000],
        ...,
        [13.5000],
        [15.7000],
        [13.0000]], dtype=torch.float64)

Siguientes pasos:
1. normalizar los datos
1. estandarizar los datos

## 1. Normalización

### Usando procedimiento automático

In [51]:
normalizador = preprocessing.MinMaxScaler()
normalizador.fit(temperatura)
normalizadaAutomatica = normalizador.transform(temperatura)
print(normalizadaAutomatica)

[[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]


### Usando procedimiento manual
Se usa la fórmula
$$
\frac{valor - mínimo}{máximo - mínimo}
$$

In [31]:
# normalizar
normalizadaManual = (temperatura-temperatura.min()) / (temperatura.max()-temperatura.min())
normalizadaManual

tensor([[0.7871],
        [0.6806],
        [0.7148],
        ...,
        [0.5133],
        [0.5970],
        [0.4943]], dtype=torch.float64)

## 2. Estandarización

### Usando procedimiento automático

In [49]:
# estándar automática
scaler = preprocessing.StandardScaler()
scaler.fit(temperatura)
estandarAutomatica = scaler.transform(temperatura)
estandarAutomatica

array([[2.33888328],
       [1.65113873],
       [1.87219948],
       ...,
       [0.5703973 ],
       [1.11076801],
       [0.44758577]])

### Usando procedimiento manual
Se usa la fórmula
$$
\frac{valor - media}{\text{desviación estándar}}
$$

In [50]:
# estándar manual
estandarManual = (temperatura - temperatura.mean()) / temperatura.std()
estandarManual

tensor([[2.3386],
        [1.6509],
        [1.8719],
        ...,
        [0.5703],
        [1.1106],
        [0.4475]], dtype=torch.float64)